version: 2.1
orbs:
  gradle: circleci/gradle@1.0.10
_defaults: &defaults
  working_directory: ~/code
  environment:
    JVM_OPTS: -Xmx3200m
commands:
  with_cache:
    description: "Caches and restores gradle dependencies"
    parameters:
      cache_key:
        type: string
        default: v1
      steps:
        type: steps
    steps:
      - restore_cache:
          key: >-
            gradle-<< parameters.cache_key >>-{{ checksum "gradle/libs.versions.toml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - steps:
          << parameters.steps >>
      - save_cache:
          key: >-
            gradle-<< parameters.cache_key >>-{{ checksum "gradle/libs.versions.toml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.konan
  gradle_publish:
    description: "Publishes to sonatype/maven central"
    parameters:
      publish_task:
        type: string
        default: publish
    steps:
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "$MAVEN_CENTRAL_SEC_RING" | base64 -d > $HOME/secring.gpg
              ./gradlew << parameters.publish_task >> -PsonatypeUsername="$SONATYPE_USERNAME" -PsonatypePassword="$SONATYPE_PASSWORD" -Psigning.keyId=34BCD878 -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg --no-parallel
            fi
jobs:
  build:
    docker:
      - image: cimg/android:2021.10.2@sha256:9685ef492705be971351614216e18b7c58a2c1885c7d92278a271d62ddea290d
    <<: *defaults
    steps:
      - checkout
      - with_cache:
          cache_key: linux
          steps:
            - run:
                name: Build
                command: ./gradlew assemble
            - run:
                name: Run Tests
                command: ./gradlew check --continue
            - gradle/collect_test_results:
                test_results_path: build/test-results
                reports_path: build/reports
            - gradle_publish
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - build:
          context: opensource-maven
          filters:
            branches:
              only: main
